### ISSUE TITLE
Ownership of Account

### ISSUE THREAD

**Issue by skilfullycurled** [crld/test-repo#1]
Hi,

I think this is my account but I've forgotten what email I set it up with so I'm hoping leaving an issue will ping myself.

Alternatively, this is not my account, and it is someone elses who has the exact same strange name as me and also is interested in machine learning and python.

If it's the latter, my apologies!

**Comment by crld** [comment]
Hello skillfullycurled,

This is my account. I don't use it often because I have a separate account for my company.

As far as the name, it's my initials!

Chris R. L. Davis
Data Engineer
_____________________________

**Comment by skilfullycurled** [comment]
Oh my gosh.  Funny. Funny. Funny.

crld is the domain name of my personal website.  Skilfullycurled was just too long and complicated so that's how I shortened it.  I choose it as a handle before I understood how many times people would have to write it to communicate with me in github.

I work in data science as well so the other repo that you forked is 100% a repo that I would have forked (or at least starred, which I will now) and doing a test-repo is something I would have done when I was trying to learn Git for the umpteenth time.

At anyrate.

Best of luck to you, feel free to delete the issue/thread if you want.

Benjamin
